config/routes.rb
Upload::Application.routes.draw do
  get "event_results/show"

  get "event_results/create"
  
  get "event_results/doug"
  post "event_results/doug"

  post "event_results/create"
  resources :results
  resources :event_results
  
  

end

app/models/event_result.rb
class EventResult < ActiveRecord::Base
    def uploaded_file=(incoming_file)
        self.filename = incoming_file.original_filename
        self.content_type = incoming_file.content_type
        self.data = incoming_file.read
    end

    def filename=(new_filename)
        write_attribute("filename", sanitize_filename(new_filename))
    end

    private
    def sanitize_filename(filename)
        #get only the filename, not the whole path (from IE)
        just_filename = File.basename(filename)
        #replace all non-alphanumeric, underscore or periods with underscores
        just_filename.gsub(/[^\w\.\-]/, '_')
    end
end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/event_results_controller.rb
class EventResultsController < ApplicationController
  def show
        @event_result = EventResult.find(params[:id])
        send_data @event_result.data, :filename => @event_result.filename, :type => @event_result.content_type, :disposition => "inline"
		# :target => "_blank" 
  end
  
  # def show
     # event_result = EventResult.find(params[:id])
	 # respond_to do |format|
        # format.html
        # #  http://guides.rubyonrails.org/action_controller_overview.html for PDF example
     # end
  # end

  # GET /event_results
  # GET /event_results.json
  def index
    @event_results = EventResult.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  
  def create
        return if params[:event_result].blank?

        @event_result = EventResult.new
        @event_result.uploaded_file = params[:event_result]

        if @event_result.save
            flash[:notice] = "Thank you for your submission..."
            redirect_to :action => "index"
        else
            flash[:error] = "There was a problem submitting your event_result."
            render :action => "new"
        end
  end
  
  
  def destroy
    @event_result = EventResult.find(params[:id])
    @event_result.destroy

    respond_to do |format|
      format.html { redirect_to '/event_results' }
      format.json { head :no_content }
    end
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.json
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render json: @result, status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_results_helper.rb
module EventResultsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/event_results/create.html.erb
<%= form_tag '/event_results/create', :multipart => true do %>
    <%= file_field_tag 'event_result' %>
    <%= submit_tag "Sendasdf Event Result" %>
<% end %>

<%= link_to 'Back', '/event_results/show' %>

app/views/event_results/doug.html.erb
<%= form_tag 'doug', :multipart => true do %>
    <%= file_field_tag 'event_result' %>
    <%= submit_tag "Send Event Result" %>
<% end %>

app/views/event_results/index.html.erb
<h1>Listing Event Results</h1>

<table>
  <tr>
    <th>FileName</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_results.each do |result| %>
  <tr>
    <td><%= result.filename %></td>
    <td><%= result.content_type %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Destroy', result, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event Result', '/event_results/create' %>

app/views/event_results/show.html.erb
<h1>EventResults#show</h1>
<p>
<% puts HellO %>
<%= puts "HellO" %>
</p>

Why nothing

<p>Find masdfasdfe in app/views/event_results/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Upload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br />
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>Filename</th>
    <th>Content type</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.filename %></td>
    <td><%= result.content_type %></td>
    <td><%= result.data %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Filename:</b>
  <%= @result.filename %>
</p>

<p>
  <b>Content type:</b>
  <%= @result.content_type %>
</p>

<p>
  <b>Data:</b>
  <%= @result.data %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>